# base images
FROM node:22-alpine

# set working directory
WORKDIR /app

# install dependencies
COPY package.json ./    
RUN npm install
RUN npm build

# copy project files
COPY . .

# expose port
EXPOSE 5173

# start app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
