# base images
FROM node:22-alpine

# set working directory
WORKDIR /app

# install dependencies
COPY package.json ./
RUN npm install

# copy project files
COPY . .

# expose port
EXPOSE 4000

# start app
CMD ["npm", "start"]





























